### ISSUE TITLE
game acting as if I'm trying to join a server when I'm trying to play single player.

### ISSUE THREAD

**Issue by CsillaAria** [GeheimagentNr1/RecipesLibrary#1]
**Versions**
Minecraft Version: 1.18.2
Minecraft Forge Version: 1.18.2 - 40.1.0
Mod Version: RecipesLibrary-1.18.2-2.0.0

**Log files**
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 5/1/22, 8:41 PM
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.advancements.Advancement.m_138325_()" because "p_135986_" is null
	at net.minecraft.server.PlayerAdvancements.m_135985_(PlayerAdvancements.java:379) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.server.PlayerAdvancements.m_135996_(PlayerAdvancements.java:372) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at glitchy_mc.ms2.procedures.UndergroundRewardProcedure.execute(UndergroundRewardProcedure.java:36) ~[MoreStones+II+v1.50.1+(1.18.2).jar%2392!/:?] {re:classloading}
	at glitchy_mc.ms2.procedures.UndergroundRewardProcedure.onAdvancement(UndergroundRewardProcedure.java:24) ~[MoreStones+II+v1.50.1+(1.18.2).jar%2392!/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_105_UndergroundRewardProcedure_onAdvancement_AdvancementEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1006) ~[forge-1.18.2-40.1.0-universal.jar%23121!/:?] {re:classloading}
	at net.minecraft.server.PlayerAdvancements.m_135988_(PlayerAdvancements.java:260) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.advancements.CriterionTrigger$Listener.m_13686_(CriterionTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.LocationTrigger.m_53645_(LocationTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:495) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.entity.MixinServerPlayer,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.PlayerAdvancements.m_135985_(PlayerAdvancements.java:379) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.server.PlayerAdvancements.m_135996_(PlayerAdvancements.java:372) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at glitchy_mc.ms2.procedures.UndergroundRewardProcedure.execute(UndergroundRewardProcedure.java:36) ~[MoreStones+II+v1.50.1+(1.18.2).jar%2392!/:?] {re:classloading}
	at glitchy_mc.ms2.procedures.UndergroundRewardProcedure.onAdvancement(UndergroundRewardProcedure.java:24) ~[MoreStones+II+v1.50.1+(1.18.2).jar%2392!/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_105_UndergroundRewardProcedure_onAdvancement_AdvancementEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1006) ~[forge-1.18.2-40.1.0-universal.jar%23121!/:?] {re:classloading}
	at net.minecraft.server.PlayerAdvancements.m_135988_(PlayerAdvancements.java:260) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.advancements.CriterionTrigger$Listener.m_13686_(CriterionTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.LocationTrigger.m_53645_(LocationTrigger.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 427
	Entity Name: Csilla_Aria
	Entity's Exact location: -36.50, 109.00, 40.50
	Entity's Block location: World: (-37,109,40), Section: (at 11,13,8 in -3,6,2; chunk contains blocks -48,-64,32 to -33,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:495) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.entity.MixinServerPlayer,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23117!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1305566336 bytes (1245 MiB) / 7516192768 bytes (7168 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Graphics card #1 name: NVIDIA GeForce RTX 2060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f11
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1215
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31114.18
	Virtual memory used (MB): 27488.65
	Swap memory total (MB): 14934.61
	Swap memory used (MB): 2217.70
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Csilla_Aria'/427, l='ServerLevel[Moon Haven]', x=-36.50, y=109.00, z=40.50]]
	Data Packs: vanilla, mod:easy_mob_farm, mod:quarkoddities (incompatible), mod:fullbrightnesstoggle, mod:supermartijn642configlib (incompatible), mod:treeharvester, mod:nourished_nether, mod:nourished_end, mod:furnish (incompatible), mod:mcwwindows, mod:sophisticatedcore (incompatible), mod:waystones (incompatible), mod:wallpapercraft (incompatible), mod:buildersdelight, mod:decorative_blocks, mod:more_stones_2, mod:sophisticatedbackpacks (incompatible), mod:mcwdoors, mod:magicaljewelry, mod:charms (incompatible), mod:balm (incompatible), mod:blueprint (incompatible), mod:forge (incompatible), mod:shetiphiancore, mod:ilikewoodxbiomesoplenty (incompatible), mod:moblocks (incompatible), mod:selene (incompatible), mod:supplementaries (incompatible), mod:clearview, mod:farmersdelight (incompatible), mod:antimobgriefing (incompatible), mod:terrablender (incompatible), mod:biomesoplenty (incompatible), mod:nekoration (incompatible), mod:material_elements, mod:mcwfences, mod:supermartijn642corelib, mod:recipes_lib, mod:domum_ornamentum (incompatible), mod:betterfpsdist (incompatible), mod:manyideas_core, mod:curios (incompatible), mod:patchouli (incompatible), mod:xaerominimap, mod:collective, mod:extlights, mod:polymorph (incompatible), mod:multibeds, mod:autoreglib (incompatible), mod:quark (incompatible), mod:angelring (incompatible), mod:tombstone, mod:manyideas_doors, mod:buildersaddition (incompatible), mod:blocksplus (incompatible), mod:worldedit (incompatible), mod:compatoplenty (incompatible), mod:mcwroofs, mod:architectury (incompatible), mod:connectedglass (incompatible), mod:byg (incompatible), mod:ilikewood, mod:ilikewoodxbyg (incompatible), mod:terraqueous, mod:cosmeticarmorreworked (incompatible), mod:exlinefurniture (incompatible), Supplementaries Virtual Resourcepack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		easy_mob_farm_1.18.2-0.4.0.jar                    |Easy Mob Farm                 |easy_mob_farm                 |0.4.0               |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		fullbrightnesstoggle_1.18.2-1.4.jar               |Full Brightness Toggle        |fullbrightnesstoggle          |1.4                 |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.18.2-5.1.jar                      |Tree Harvester                |treeharvester                 |5.1                 |DONE      |Manifest: NOSIGNATURE
		NourishedNetherV12.jar                            |Nourished Nether              |nourished_nether              |1.1.3               |DONE      |Manifest: NOSIGNATURE
		EnlightenedEndV10.jar                             |Enlightened End               |nourished_end                 |1.0.9               |DONE      |Manifest: NOSIGNATURE
		furnish-1.18-0.5-fix3.jar                         |Furnish                       |furnish                       |1.18-0.5-fix3       |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.3-mc1.18.2.jar                    |Macaw's Windows               |mcwwindows                    |2.0.3               |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.0.5.12.jar             |Sophisticated Core            |sophisticatedcore             |1.18.2-0.0.5.12     |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.0.0.jar                 |Waystones                     |waystones                     |10.0.0              |DONE      |Manifest: NOSIGNATURE
		WallpaperCraft-1.18.1-1.6.1.jar                   |Wallpapercraft                |wallpapercraft                |1.6.1               |DONE      |Manifest: NOSIGNATURE
		BuildersDelight-1.18.2-v.0.9.3.jar                |Builder's Delight             |buildersdelight               |0.9                 |DONE      |Manifest: NOSIGNATURE
		Decorative+Blocks-forge-1.18.2-2.1.0.jar          |Decorative Blocks             |decorative_blocks             |2.1.0               |DONE      |Manifest: NOSIGNATURE
		MoreStones+II+v1.50.1+(1.18.2).jar                |More Stones II                |more_stones_2                 |1.50.1              |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.15.18.570.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.15.18.570  |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.6-mc1.18.2.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.6               |DONE      |Manifest: NOSIGNATURE
		magicaljewelry-1.18.2_1.4.2.jar                   |Magical Jewelry               |magicaljewelry                |1.18.2_1.4.2        |DONE      |Manifest: NOSIGNATURE
		charms-1.18.2-1.1.1.jar                           |Charms                        |charms                        |1.18.2-1.1.0        |DONE      |Manifest: NOSIGNATURE
		balm-3.0.2+0.jar                                  |Balm                          |balm                          |3.0.2+0             |DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.3.2.jar                        |Blueprint                     |blueprint                     |5.3.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.0-universal.jar                 |Forge                         |forge                         |40.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		shetiphiancore-1.18-3.10.8.jar                    |ShetiPhian-Core               |shetiphiancore                |3.10.8              |DONE      |Manifest: NOSIGNATURE
		ilikewoodxbiomesoplenty-1.18.2-8.0.0.jar          |I Like Wood - Biomes o' Plenty|ilikewoodxbiomesoplenty       |1.18.2-8.0.0        |DONE      |Manifest: NOSIGNATURE
		moblocks-0.10.3b.jar                              |Mo'Blocks                     |moblocks                      |0.10.3b             |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.15.5.jar                          |Selene                        |selene                        |1.18.2-1.15.5       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.3.7.jar                  |Supplementaries               |supplementaries               |1.18.2-1.3.7        |DONE      |Manifest: NOSIGNATURE
		LavaClearView-1.18.2-forge-4.0.1.jar              |Lava Clear View               |clearview                     |4.0.1               |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.2-1.0.4.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.0.4        |DONE      |Manifest: NOSIGNATURE
		antimobgriefing-1.18.2-1.0.0.jar                  |Anti Mobgriefing              |antimobgriefing               |1.18.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.99.jar            |TerraBlender                  |terrablender                  |1.18.2-1.1.0.99     |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.109-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.109   |DONE      |Manifest: NOSIGNATURE
		nekoration-1.18.X-1.6.1.jar                       |Nekoration                    |nekoration                    |1.6.1               |DONE      |Manifest: NOSIGNATURE
		material_elements_1.18.2-3.2.0.jar                |Material Elements             |material_elements             |3.2.0               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.4-mc1.18.2.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.4               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.18-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.18              |DONE      |Manifest: NOSIGNATURE
		RecipesLibrary-1.18.2-2.0.0.jar                   |Recipes Library               |recipes_lib                   |2.0.0               |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.2-1.0.50-ALPHA |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.18.2-1.5.jar                      |betterfpsdist mod             |betterfpsdist                 |1.18.2-1.5          |DONE      |Manifest: NOSIGNATURE
		ManyIdeasCore-1.18.2-1.2.0.jar                    |Many Ideas Core               |manyideas_core                |1.2.0               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.0.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-67.jar                           |Patchouli                     |patchouli                     |1.18.2-67           |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.6.0_Forge_1.18.2.jar            |Xaero's Minimap               |xaerominimap                  |22.6.0              |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-4.25.jar                        |Collective                    |collective                    |4.25                |DONE      |Manifest: NOSIGNATURE
		extlights-4.4.jar                                 |Extended Lights               |extlights                     |4.4                 |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.1-0.43.jar                   |Polymorph                     |polymorph                     |1.18.1-0.43         |DONE      |Manifest: NOSIGNATURE
		multibeds-1.18-1.9.5.jar                          |Multi-Beds                    |multibeds                     |1.9.5               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-353.jar                                 |Quark                         |quark                         |3.2-353             |DONE      |Manifest: NOSIGNATURE
		angelring-1.18-1.5.0.jar                          |Angel Ring                    |angelring                     |1.5.0               |DONE      |Manifest: NOSIGNATURE
		tombstone-7.4.5-1.18.2.jar                        |Corail Tombstone              |tombstone                     |7.4.5               |DONE      |Manifest: NOSIGNATURE
		ManyIdeasDoors-1.18.2-1.2.0.jar                   |Many Ideas Doors              |manyideas_doors               |1.2.0               |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.18.2-20220308a.jar             |Builders Crafts & Addition    |buildersaddition              |1.18.2-20220308a    |DONE      |Manifest: NOSIGNATURE
		Blocks+++1.18.1+-+1.4.jar                         |Blocks +                      |blocksplus                    |1.4                 |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.10.jar                          |WorldEdit                     |worldedit                     |7.2.10+1742f98      |DONE      |Manifest: NOSIGNATURE
		Compat-O-Plenty-1.18.2-1.5.0.jar                  |Compat O' Plenty              |compatoplenty                 |1.18.2-1.5.0        |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.1.2-mc1.18.2.jar                      |Macaw's Roofs                 |mcwroofs                      |2.1.2               |DONE      |Manifest: NOSIGNATURE
		architectury-4.3.53.jar                           |Architectury                  |architectury                  |4.3.53              |DONE      |Manifest: NOSIGNATURE
		connectedglass-1.1.3-mc1.18.jar                   |Connected Glass               |connectedglass                |1.1.3               |DONE      |Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-11-all|Oh The Biomes You'll Go       |byg                           |1.4                 |DONE      |Manifest: NOSIGNATURE
		ilikewood-1.18.2-8.5.0.2.jar                      |I Like Wood                   |ilikewood                     |1.18.2-8.5.0.2      |DONE      |Manifest: NOSIGNATURE
		ilikewoodxbyg-1.18.2-8.0.0.jar                    |I Like Wood - Oh The Biomes Yo|ilikewoodxbyg                 |1.18.2-8.0.0        |DONE      |Manifest: NOSIGNATURE
		terraqueous-1.18-1.9.9.jar                        |Terraqueous                   |terraqueous                   |1.9.9               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.2-v2.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		exlinefurniture-forge-1.18.2-v2.05.jar            |Exline's Furniture            |exlinefurniture               |1.18.2              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 812f3d8b-5149-4a64-90fa-2cd3fee6bc82
	FML: 40.1
	Forge: net.minecraftforge:40.1.0

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
I'm trying to create a single player world, but the game keeps acting as if I'm trying to join a server I think?

**Screenshots**

**Additional context**
I think it's haveing some kind of reaction with one or more other mods, and I've been trying all day to find out what mod. I thought someone who actually understood modding might have a better idea of what was going on  if they saw a crash report.

**Comment by CsillaAria** [comment]
Sorry it seemed like it was this mod, but now something else is causing the same issue.
